spell_array = [
  {
    incantation: 'Aqua Eructo',
    magic_type: 'Charm',
    effect: 'attacks opponent with a jet of water',
    level: 1,
    damage: 10,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Fumos',
    magic_type: 'Defensive',
    effect: 'creates a protective smokescreen',
    level: 1,
    damage: 0,
    recovery: 0,
    obscures: true,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Jelly-Brain Jinx',
    magic_type: 'Jinx',
    effect: 'confuses the opponent',
    level: 1,
    damage: 5,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Ferula',
    magic_type: 'Healing',
    effect: 'heals 10 health points',
    level: 1,
    damage: 0,
    recovery: 10,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Conjunctivitis',
    magic_type: 'Curse',
    effect: 'causes irritation in the eyes',
    level: 1,
    damage: 10,
    recovery: 0,
    obscures: true,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Immobulus',
    magic_type: 'Charm',
    effect: 'renders the opponent immobile',
    level: 2,
    damage: 10,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Nebulus',
    magic_type: 'Jinx',
    level: 3,
    effect: 'creates a fog that makes the caster invisible',
    damage: 0,
    recovery: 5,
    obscures: true,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Fianto Duri',
    magic_type: 'Defensive',
    effect: 'creates a stone protective barrier',
    level: 4,
    damage: 0,
    recovery: 10,
    obscures: true,
    reveals: false,
    protects: 1,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Episkey',
    magic_type: 'Healing',
    effect: 'heals 15 health points',
    level: 5,
    damage: 0,
    recovery: 20,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Petrificus Totalus',
    magic_type: 'Curse',
    effect: 'freezes the opponent',
    level: 6,
    damage: 10,
    recovery: 5,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Disillusionment Charm',
    magic_type: 'Charm',
    effect: 'makes the caster invisible',
    level: 7,
    damage: 0,
    recovery: 10,
    obscures: true,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Protego Maxima',
    magic_type: 'Defensive',
    effect: 'creates a protective barrier',
    level: 8,
    damage: 0,
    recovery: 15,
    obscures: false,
    reveals: false,
    protects: 1,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Jelly-Fingers Jinx',
    magic_type: 'Jinx',
    effect: 'causes the opponent to drop their wand',
    level: 9,
    damage: 0,
    recovery: 10,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Salvia Hexia',
    magic_type: 'Healing',
    effect: 'heals 30 health points',
    level: 10,
    damage: 0,
    recovery: 30,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Reducto',
    magic_type: 'Curse',
    effect: "destroys opponent's protective shields",
    level: 11,
    damage: nil,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 1,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Diffindo',
    magic_type: 'Charm',
    effect: 'slashes at the opponent',
    level: 12,
    damage: 20,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Expelliarmus',
    magic_type: 'Defensive',
    effect: 'disarms the opponent',
    level: 13,
    damage: 15,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Levicorpus',
    magic_type: 'Jinx',
    effect: 'upends and disarms the opponent',
    level: 14,
    damage: 15,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Vulnera Sanentur',
    magic_type: 'Healing',
    effect: 'heals 40 health points',
    level: 15,
    damage: 0,
    recovery: 40,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Sectumsempra',
    magic_type: 'Curse',
    effect: 'creates deep gashes in the opponent',
    level: 16,
    damage: 25,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Alarte Ascendare',
    magic_type: 'Charm',
    effect: 'sends the opponent into the air',
    level: 17,
    damage: 25,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Liberacorpus',
    magic_type: 'Defensive',
    effect: 'frees from bonds',
    level: 18,
    damage: 0,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 1,
    stuns: false,
    revives: true,
    dark_magic: false
  },
  {
    incantation: 'Incarcerous',
    magic_type: 'Jinx',
    effect: 'binds the opponent in ropes',
    level: 19,
    damage: 20,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 1,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Expulso',
    magic_type: 'Curse',
    effect: 'creates a pressurized explosion',
    level: 20,
    damage: 25,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Incendio',
    magic_type: 'Charm',
    effect: 'conjures a blaze of fire',
    level: 21,
    damage: 30,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Stupefy',
    magic_type: 'Defensive',
    effect: 'stuns the opponent',
    level: 22,
    damage: 25,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Stinging Jinx',
    magic_type: 'Jinx',
    effect: 'causes painful inflammation of the skin',
    level: 23,
    damage: 30,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Bombarda Maxima',
    magic_type: 'Charm',
    effect: 'creates a large explosion',
    level: 24,
    damage: 40,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Confringo',
    magic_type: 'Curse',
    effect: 'creates a firey explosion',
    level: 25,
    damage: 40,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Rennervate',
    magic_type: 'Defensive',
    effect: 'revives caster if they are stunned',
    level: 26,
    damage: 0,
    recovery: 15,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: true,
    dark_magic: false
  },
  {
    incantation: 'Flipendo',
    magic_type: 'Jinx',
    effect: 'violently throws the opponent backwards',
    level: 27,
    damage: 35,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Homenum Revelio',
    magic_type: 'Defensive',
    effect: 'reveals invisible opponents',
    level: 28,
    damage: 0,
    recovery: 0,
    obscures: false,
    reveals: true,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: false
  },
  {
    incantation: 'Fiendfyre',
    magic_type: 'Jinx',
    effect: 'creates beasts made of fire that attack the opponent',
    level: 29,
    damage: 45,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Finite Incantatum',
    magic_type: 'Charm',
    effect: 'ends the effects of all spells',
    level: 30,
    damage: 0,
    recovery: 0,
    obscures: false,
    reveals: true,
    protects: 0,
    exposes: 1,
    binds: 0,
    unbinds: 1,
    stuns: false,
    revives: true,
    dark_magic: false
  },
  {
    incantation: 'Crucio',
    magic_type: 'Curse',
    effect: 'causes extreme pain',
    level: 31,
    damage: 60,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: true,
    revives: false,
    dark_magic: true
  },
  {
    incantation: 'Avada Kedavra',
    magic_type: 'Curse',
    effect: 'kills the opponent',
    level: 32,
    damage: 75,
    recovery: 0,
    obscures: false,
    reveals: false,
    protects: 0,
    exposes: 0,
    binds: 0,
    unbinds: 0,
    stuns: false,
    revives: false,
    dark_magic: true
  }
]
